version: '3'
services:
    amrs:
        container_name: amrs
        image: ampathke/openmrs2.5.1:prod-tc9-jdk11-v0.0.5
        depends_on:
        - db
        env_file: ./main.env
        volumes:
            - ./amrs:/root/.OpenMRS
        restart: unless-stopped
        ports:
            - 8083:8080
        dns:
           - 8.8.8.8
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8083/amrs/"]
            timeout: 20s
    db:
      image: mysql:5.6
      command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
      environment:
        MYSQL_DATABASE: openmrs
        MYSQL_ROOT_PASSWORD: Admin123
        MYSQL_USER: openmrs
        MYSQL_PASSWORD: Admin123
      volumes:
        - db-data:/var/lib/mysql
volumes:
  db-data: